-- Which Level Mods are assigned to which levels/jobs, level IDs are checked first, then the job ID (used for multi-day heists)
local level_mod_map = {
	jewelry_store = "CS_normal",  -- Jewelry Store
	four_stores = "CS_normal",  -- Four Stores
	nightclub = "CS_normal",  -- Nightclub
	mallcrasher = "CS_normal",  -- Mallcrasher
	ukrainian_job_prof = "CS_normal",  -- Ukrainian Job
	branchbank_deposit = "CS_normal",  -- Bank Heist: Deposit
	branchbank_cash = "CS_normal",  -- Bank Heist: Cash
	branchbank_prof = "CS_normal",  -- Bank Heist: Random
	branchbank_gold_prof = "CS_normal",  -- Bank Heist: Gold
	firestarter = "FBI_overkill_145",  -- Firestarter
	alex = "FBI_overkill_145",  -- Rats
	watchdogs = "FBI_overkill_145",  -- Watchdogs
	watchdogs_night = "FBI_overkill_145",  -- Watchdogs (night)
	framing_frame = "FBI_overkill_145",  -- Framing Frame
	welcome_to_the_jungle_prof = "FBI_overkill_145",  -- Big Oil
	welcome_to_the_jungle_night_prof = "FBI_overkill_145",  -- Big Oil (night)
	family = "CS_normal",  -- Diamond Store
	election_day = "FBI_overkill_145",  -- Election Day
	election_day_1 = "CS_FBI_overkill",  -- Election Day (day 1 override)
	arm_fac = "CITY_overkill_290",  -- Transport: Harbor
	arm_par = "CITY_overkill_290",  -- Transport: Park
	arm_hcm = "CITY_overkill_290",  -- Transport: Downtown
	arm_und = "CITY_overkill_290",  -- Transport: Underpass
	arm_cro = "CITY_overkill_290",  -- Transport: Crossroads
	arm_for = "CITY_overkill_290",  -- Transport: Train
	big = "CS_FBI_overkill",  -- Big Bank
	mia = "CS_normal",  -- Hotline Miami
	gallery = "CS_normal",  -- Art Gallery
	hox = "FBI_overkill_145",  -- Hoxton Breakout
	hox_3 = "FBI_overkill_145",  -- Hoxton Revenge
	pines = "FBI_overkill_145",  -- White Xmas
	mus = "CS_FBI_overkill",  -- The Diamond
	crojob1 = "FBI_overkill_145",  -- The Bomb: Dockyard
	crojob2 = "FBI_overkill_145",  -- The Bomb: Forest
	crojob2_night = "FBI_overkill_145",  -- The Bomb: Forest (night)
	rat = "FBI_overkill_145",  -- Cook Off
	shoutout_raid = "FBI_overkill_145",  -- Meltdown
	arena = "CITY_overkill_290",  -- The Alesso Heist
	kenaz = "FBI_overkill_145",  -- Golden Grin Casino
	jolly = "FBI_overkill_145",  -- Aftershock
	red2 = "CS_normal",  -- First World Bank
	dinner = "FBI_CITY_easy_wish",  -- Slaughterhouse
	nail = "FBI_overkill_145",  -- Lab Rats
	cane = "CS_normal",  -- Santa's Workshop
	pbr = "CS_normal",  -- Beneath the Mountain
	pbr2 = "FBI_overkill_145",  -- Birth of Sky
	peta = "FBI_overkill_145",  -- Goat Simulator
	peta1 = "CS_FBI_overkill",  -- Goat Simulator (day 1 override)
	pal = "CS_normal",  -- Counterfeit
	man = "FBI_overkill_145",  -- Undercover
	mad = "FBI_overkill_145",  -- Boiling Point
	born = "FBI_overkill_145",  -- Biker Heist
	chill_combat = "FBI_overkill_145",  -- Safehouse Raid
	friend = "FBI_overkill_145",  -- Scarface Mansion
	flat = "CS_FBI_overkill",  -- Panic Room
	help = "FBI_overkill_145",  -- Prison Nightmare
	spa = "CS_normal",  -- Brooklyn 10-10
	moon = "CS_normal",  -- Stealing Xmas
	run = "CS_normal",  -- Heat Street
	glace = "CS_FBI_overkill",  -- Green Bridge
	dah = "CITY_overkill_290",  -- Diamond Heist
	rvd = "CS_normal",  -- Reservoir Dogs
	hvh = "CS_FBI_overkill",  -- Cursed Kill Room
	wwh = "CS_normal",  -- Alaskan Deal
	brb = "CS_normal",  -- Brooklyn Bank
	des = "FBI_overkill_145",  -- Henry's Rock
	nmh = "CITY_overkill_290",  -- No Mercy
	sah = "FBI_overkill_145",  -- Shacklethorne Auction
	vit = "CITY_overkill_290",  -- The White House
	bph = "CITY_overkill_290",  -- Hell's Island
	mex = "CITY_overkill_290",  -- Border Crossing
	mex_cooking = "CITY_overkill_290",  -- Border Crystals
	bex = "CS_normal",  -- San Martin Bank
	pex = "FBI_overkill_145",  -- Breakfast in Tijuana
	fex = "CITY_overkill_290",  -- Buluc's Mansion
	chas = "CS_normal",  -- Dragon Heist
	sand = "CS_FBI_overkill",  -- The Ukrainian Prisoner
	chca = "FBI_overkill_145",  -- Black Cat
	pent = "FBI_CITY_easy_wish",  -- Mountain Master
	ranc = "CS_FBI_overkill",  -- Midland Ranch
	trai = "FBI_overkill_145",  -- Lost in Transit
	corp = "FBI_CITY_easy_wish",  -- Hostile Takeover
	deep = "CITY_overkill_290",  -- Crude Awakening
	roberts = "CS_normal",  -- GO Bank

	-- Custom heists
	["branchbank_russia"] = "CS_FBI_overkill",  -- Bank Heist: Russia, https://modworkshop.net/mod/30389
	["rusw"] = "FBI_overkill_145",  -- Scorched Earth, https://modworkshop.net/mod/43578
	["rusd"] = "CS_FBI_overkill",  -- Cold Stones, https://modworkshop.net/mod/43578
	["ahop"] = "CS_FBI_overkill",  -- A House of Pleasure, https://modworkshop.net/mod/43578
	["crimepunish"] = "FBI_overkill_145",  -- Crime and Punishment, https://modworkshop.net/mod/43578
	["flatline_nar"] = "CS_FBI_overkill",  -- Flatline, https://modworkshop.net/mod/43578
	["Hunter_narrative"] = "FBI_overkill_145",  -- Hunter and Hunted, https://modworkshop.net/mod/43578
	["constantine_penthouse_nar"] = "CITY_overkill_290",  -- Penthouse Crasher, https://modworkshop.net/mod/43578
	["constantine_resort_nar"] = "CITY_overkill_290",  -- Scarlett Resort, https://modworkshop.net/mod/43578
	["Avalon's Shadow"] = "CITY_overkill_290",  -- Avalon's Shadow, https://modworkshop.net/mod/34760
	["thechase"] = "CS_FBI_overkill",  -- Stalk Fraud, https://modworkshop.net/mod/24638
	["physics"] = "CITY_overkill_290",  -- BOWORKS, https://modworkshop.net/mod/31560
	["physics_citystreets"] = "CS_normal",  -- BOWORKS (day 1)
	["physics_tower"] = "FBI_overkill_145",  -- BOWORKS (day 2)
	["physics_core"] = "CITY_overkill_290",  -- BOWORKS (day 3)
	["narr_friday"] = "FBI_CITY_easy_wish",  -- Crashing Capitol, https://modworkshop.net/mod/44630
	["bnktower"] = "CITY_overkill_290",  -- GenSec H.I.V.E, https://modworkshop.net/mod/36368
}

return level_mod_map
