return {
	-- harasser spawns on container tops
	[104446] = { enemy = tweak_data.levels:moon_random_unit("swats"), },  -- swat
	[104447] = { enemy = tweak_data.levels:moon_random_unit("swats"), },
	[104582] = { enemy = tweak_data.levels:moon_random_unit("swats"), },
	[104584] = { enemy = tweak_data.levels:moon_random_unit("swats"), },
	[104585] = { enemy = tweak_data.levels:moon_random_unit("swats"), },
	[104787] = { enemy = tweak_data.levels:moon_random_unit("swats"), },
	[104941] = { enemy = tweak_data.levels:moon_random_unit("swats"), },
	[104942] = { enemy = tweak_data.levels:moon_random_unit("swats"), },
	[104943] = { enemy = tweak_data.levels:moon_random_unit("swats"), },
	[104944] = { enemy = tweak_data.levels:moon_random_unit("swats"), },
	[101731] = { enemy = tweak_data.levels:moon_random_unit("swats"), },
	[103516] = { enemy = tweak_data.levels:moon_random_unit("swats"), },
	[104452] = { enemy = tweak_data.levels:moon_random_unit("swats"), },
	[104469] = { enemy = tweak_data.levels:moon_random_unit("swats"), },
	[104986] = { enemy = tweak_data.levels:moon_random_unit("swats"), },
	[101531] = { enemy = tweak_data.levels:moon_random_unit("swats"), },  -- fbi
	[101532] = { enemy = tweak_data.levels:moon_random_unit("swats"), },
	[101534] = { enemy = tweak_data.levels:moon_random_unit("swats"), },
	[101738] = { enemy = tweak_data.levels:moon_random_unit("swats"), },
	[101739] = { enemy = tweak_data.levels:moon_random_unit("swats"), },
	[102012] = { enemy = tweak_data.levels:moon_random_unit("swats"), },
	[102888] = { enemy = tweak_data.levels:moon_random_unit("swats"), },
	[102889] = { enemy = tweak_data.levels:moon_random_unit("swats"), },
	[102890] = { enemy = tweak_data.levels:moon_random_unit("swats"), },
	[102891] = { enemy = tweak_data.levels:moon_random_unit("swats"), },
	[104372] = { enemy = tweak_data.levels:moon_random_unit("swats"), },
	[104375] = { enemy = tweak_data.levels:moon_random_unit("swats"), },
	[104376] = { enemy = tweak_data.levels:moon_random_unit("swats"), },
	[104378] = { enemy = tweak_data.levels:moon_random_unit("swats"), },
	[104433] = { enemy = tweak_data.levels:moon_random_unit("swats"), },
	[102353] = { enemy = tweak_data.levels:moon_random_unit("swats"), },  -- city
	[102355] = { enemy = tweak_data.levels:moon_random_unit("swats"), },
	[102356] = { enemy = tweak_data.levels:moon_random_unit("swats"), },
	[102357] = { enemy = tweak_data.levels:moon_random_unit("swats"), },
	[102359] = { enemy = tweak_data.levels:moon_random_unit("swats"), },
	[102360] = { enemy = tweak_data.levels:moon_random_unit("swats"), },
	[102892] = { enemy = tweak_data.levels:moon_random_unit("swats"), },
	[102893] = { enemy = tweak_data.levels:moon_random_unit("swats"), },
	[102894] = { enemy = tweak_data.levels:moon_random_unit("swats"), },
	[102895] = { enemy = tweak_data.levels:moon_random_unit("swats"), },
	[104473] = { enemy = tweak_data.levels:moon_random_unit("swats"), },
	[104856] = { enemy = tweak_data.levels:moon_random_unit("swats"), },
	[104856] = { enemy = tweak_data.levels:moon_random_unit("swats"), },
	[104858] = { enemy = tweak_data.levels:moon_random_unit("swats"), },
	[104859] = { enemy = tweak_data.levels:moon_random_unit("swats"), },
	[104860] = { enemy = tweak_data.levels:moon_random_unit("swats"), },
	[102473] = { enemy = tweak_data.levels:moon_random_unit("swats"), },  -- zeal
	[102877] = { enemy = tweak_data.levels:moon_random_unit("swats"), },
	[102878] = { enemy = tweak_data.levels:moon_random_unit("swats"), },
	[102885] = { enemy = tweak_data.levels:moon_random_unit("swats"), },
	[102886] = { enemy = tweak_data.levels:moon_random_unit("swats"), },
	[102887] = { enemy = tweak_data.levels:moon_random_unit("swats"), },
	[102896] = { enemy = tweak_data.levels:moon_random_unit("swats"), },
	[102897] = { enemy = tweak_data.levels:moon_random_unit("swats"), },
	[102898] = { enemy = tweak_data.levels:moon_random_unit("swats"), },
	[104365] = { enemy = tweak_data.levels:moon_random_unit("swats"), },
	[104861] = { enemy = tweak_data.levels:moon_random_unit("swats"), },
	[104863] = { enemy = tweak_data.levels:moon_random_unit("swats"), },
	[104867] = { enemy = tweak_data.levels:moon_random_unit("swats"), },
	[104868] = { enemy = tweak_data.levels:moon_random_unit("swats"), },
	[104873] = { enemy = tweak_data.levels:moon_random_unit("swats"), },

	-- corridor dozers
	[102404] = { enemy = tweak_data.levels:moon_random_unit("dozers_no_med"), },
	[102407] = { enemy = tweak_data.levels:moon_random_unit("dozers_no_med"), },
	[102410] = { enemy = tweak_data.levels:moon_random_unit("dozers_no_med"), },
	[102413] = { enemy = tweak_data.levels:moon_random_unit("dozers_no_med"), },
	[102402] = { enemy = tweak_data.levels:moon_random_unit("dozers_no_med"), },
	[102408] = { enemy = tweak_data.levels:moon_random_unit("dozers_no_med"), },
	[102409] = { enemy = tweak_data.levels:moon_random_unit("dozers_no_med"), },
	[102414] = { enemy = tweak_data.levels:moon_random_unit("dozers_no_med"), },
	[102405] = { enemy = tweak_data.levels:moon_random_unit("dozers_no_med"), },
	[102406] = { enemy = tweak_data.levels:moon_random_unit("dozers_no_med"), },
	[102411] = { enemy = tweak_data.levels:moon_random_unit("dozers_no_med"), },
	[102412] = { enemy = tweak_data.levels:moon_random_unit("dozers_no_med"), },
}
