return {
	-- cops
	[100426] = { enemy = tweak_data.levels:moon_random_unit("cops_light"), },  -- immediately on the scene
	[100247] = { enemy = tweak_data.levels:moon_random_unit("cops_light"), },
	[100450] = { enemy = tweak_data.levels:moon_random_unit("cops_light"), },
	[100434] = { enemy = tweak_data.levels:moon_random_unit("cops_light"), },
	[100438] = { enemy = tweak_data.levels:moon_random_unit("cops_light"), },
	[100448] = { enemy = tweak_data.levels:moon_random_unit("cops_light"), },
	[100524] = { enemy = tweak_data.levels:moon_random_unit("cops_light"), },
	[100540] = { enemy = tweak_data.levels:moon_random_unit("cops_light"), },
	[100520] = { enemy = tweak_data.levels:moon_random_unit("cops_light"), },
	[100494] = { enemy = tweak_data.levels:moon_random_unit("cops_light"), },
	[100477] = { enemy = tweak_data.levels:moon_random_unit("cops_light"), },
	[106047] = { enemy = tweak_data.levels:moon_random_unit("cops_light"), },
	[106045] = { enemy = tweak_data.levels:moon_random_unit("cops_light"), },
	[106052] = { enemy = tweak_data.levels:moon_random_unit("cops_light"), },
	[100430] = { enemy = tweak_data.levels:moon_random_unit("cops_medium"), },  -- just arriving on the scene
	[100553] = { enemy = tweak_data.levels:moon_random_unit("cops_medium"), },
	[100432] = { enemy = tweak_data.levels:moon_random_unit("cops_medium"), },
	[100557] = { enemy = tweak_data.levels:moon_random_unit("cops_medium"), },
	[100560] = { enemy = tweak_data.levels:moon_random_unit("cops_medium"), },
	[100526] = { enemy = tweak_data.levels:moon_random_unit("cops_medium"), },
	[100528] = { enemy = tweak_data.levels:moon_random_unit("cops_medium"), },
	[100555] = { enemy = tweak_data.levels:moon_random_unit("cops_medium"), },
	[100554] = { enemy = tweak_data.levels:moon_random_unit("cops_medium"), },
	[100483] = { enemy = tweak_data.levels:moon_random_unit("cops_medium"), },
	[100543] = { enemy = tweak_data.levels:moon_random_unit("cops_medium"), },
	[100556] = { enemy = tweak_data.levels:moon_random_unit("cops_medium"), },
	[100550] = { enemy = tweak_data.levels:moon_random_unit("cops_heavy"), },  -- at police lines
	[100551] = { enemy = tweak_data.levels:moon_random_unit("cops_heavy"), },
	[100549] = { enemy = tweak_data.levels:moon_random_unit("cops_heavy"), },
	[100454] = { enemy = tweak_data.levels:moon_random_unit("cops_heavy"), },
	[100452] = { enemy = tweak_data.levels:moon_random_unit("cops_heavy"), },
	[106057] = { enemy = tweak_data.levels:moon_random_unit("cops_heavy"), },
	[106059] = { enemy = tweak_data.levels:moon_random_unit("cops_heavy"), },
	[106054] = { enemy = tweak_data.levels:moon_random_unit("cops_heavy"), },
	[106051] = { enemy = tweak_data.levels:moon_random_unit("cops_heavy"), },
	[100552] = { enemy = tweak_data.levels:moon_random_unit("cops"), },  -- garden/alley
	[100558] = { enemy = tweak_data.levels:moon_random_unit("cops"), },
	[100570] = { enemy = tweak_data.levels:moon_random_unit("cops"), },
	[100545] = { enemy = tweak_data.levels:moon_random_unit("cops"), },
	[106244] = { enemy = tweak_data.levels:moon_random_unit("cops"), },
	[106243] = { enemy = tweak_data.levels:moon_random_unit("cops"), },
	[100546] = { enemy = tweak_data.levels:moon_random_unit("cops"), },
	[106246] = { enemy = tweak_data.levels:moon_random_unit("cops"), },
	[100544] = { enemy = tweak_data.levels:moon_random_unit("cops"), },
	[106245] = { enemy = tweak_data.levels:moon_random_unit("cops"), },
	[100559] = { enemy = tweak_data.levels:moon_random_unit("cops"), },
	[106227] = { enemy = tweak_data.levels:moon_random_unit("fbis"), },  -- cops spawning out of the playable area ("copX_ABC"),, replaced with fbi agents
	[106232] = { enemy = tweak_data.levels:moon_random_unit("fbis"), },
	[106236] = { enemy = tweak_data.levels:moon_random_unit("fbis"), },
	[106240] = { enemy = tweak_data.levels:moon_random_unit("fbis"), },
	[106248] = { enemy = tweak_data.levels:moon_random_unit("fbis"), },
	[106252] = { enemy = tweak_data.levels:moon_random_unit("fbis"), },
	[106230] = { enemy = tweak_data.levels:moon_random_unit("fbis"), },
	[106231] = { enemy = tweak_data.levels:moon_random_unit("fbis"), },
	[106235] = { enemy = tweak_data.levels:moon_random_unit("fbis"), },
	[106239] = { enemy = tweak_data.levels:moon_random_unit("fbis"), },
	[106247] = { enemy = tweak_data.levels:moon_random_unit("fbis"), },
	[106251] = { enemy = tweak_data.levels:moon_random_unit("fbis"), },
	[106228] = { enemy = tweak_data.levels:moon_random_unit("fbis"), },
	[106233] = { enemy = tweak_data.levels:moon_random_unit("fbis"), },
	[106237] = { enemy = tweak_data.levels:moon_random_unit("fbis"), },
	[106241] = { enemy = tweak_data.levels:moon_random_unit("fbis"), },
	[106249] = { enemy = tweak_data.levels:moon_random_unit("fbis"), },
	[106253] = { enemy = tweak_data.levels:moon_random_unit("fbis"), },
	[106229] = { enemy = tweak_data.levels:moon_random_unit("fbis"), },
	[106234] = { enemy = tweak_data.levels:moon_random_unit("fbis"), },
	[106238] = { enemy = tweak_data.levels:moon_random_unit("fbis"), },
	[106242] = { enemy = tweak_data.levels:moon_random_unit("fbis"), },
	[106250] = { enemy = tweak_data.levels:moon_random_unit("fbis"), },
	[106254] = { enemy = tweak_data.levels:moon_random_unit("fbis"), },
}
