return {
	jewelry_store = "CS_normal",  -- jewelry store
	four_stores = "CS_normal",  -- four stores
	nightclub = "CS_normal",  -- nightclub
	mallcrasher = "CS_normal",  -- mallcrasher
	ukrainian_job_prof = "CS_normal",  -- ukrainian job
	branchbank_deposit = "CS_normal",  -- bank heist deposit
	branchbank_cash = "CS_normal",  -- bank heist cash
	branchbank_prof = "CS_normal",  -- bank heist random
	branchbank_gold_prof = "CS_normal",  -- bank heist gold
	firestarter = "FBI_overkill_145",  -- firestarter
	alex = "FBI_overkill_145",  -- rats
	watchdogs = "FBI_overkill_145",  -- watchdogs
	watchdogs_night = "FBI_overkill_145",  -- watchdogs
	framing_frame = "FBI_overkill_145",  -- framing frame (days 2 and 3)
	welcome_to_the_jungle_prof = "FBI_overkill_145",  -- big oil
	welcome_to_the_jungle_night_prof = "FBI_overkill_145",  -- big oil
	family = "CS_normal",  -- diamond store
	election_day = "FBI_overkill_145",  -- election day (day 2 and plan c)
	election_day_1 = "CS_FBI_overkill",  -- election day day 1 override
	arm_fac = "CITY_overkill_290",  -- transport harbor
	arm_par = "CITY_overkill_290",  -- transport park
	arm_hcm = "CITY_overkill_290",  -- transport downtown
	arm_und = "CITY_overkill_290",  -- transport underpass
	arm_cro = "CITY_overkill_290",  -- transport crossroads
	arm_for = "CITY_overkill_290",  -- transport train
	big = "CS_FBI_overkill",  -- big bank
	mia = "CS_normal",  -- hotline miami
	gallery = "CS_normal",  -- art gallery
	hox = "FBI_overkill_145",  -- hoxton breakout (day 1)
	hox_2 = "FBI_with_office",  -- hoxton breakout day 2 override
	hox_3 = "FBI_mcmansion",  -- hoxton revenge
	pines = "FBI_overkill_145",  -- white xmas
	mus = "CS_FBI_overkill",  -- the diamond
	crojob1 = "FBI_overkill_145",  -- bomb dockyard
	crojob2 = "FBI_overkill_145",  -- bomb forest
	crojob2_night = "FBI_overkill_145",  -- bomb forest
	rat = "FBI_overkill_145",  -- cook off
	shoutout_raid = "FBI_overkill_145",  -- meltdown
	arena = "CITY_overkill_290",  -- alesso heist
	kenaz = "FBI_overkill_145",  -- golden grin casino
	jolly = "FBI_overkill_145",  -- aftershock
	red2 = "CS_normal",  -- first world bank
	dinner = "FBI_CITY_easy_wish",  -- slaughterhouse
	nail = "FBI_overkill_145",  -- lab rats
	cane = "FBI_overkill_145",  -- santas workshop
	pbr2 = "FBI_overkill_145",  -- birth of sky
	peta = "CS_FBI_overkill",  -- goat simulator (day 1)
	peta2 = "FBI_overkill_145",  -- goat simulator day 2 override
	pal = "CS_normal",  -- counterfeit
	man = "FBI_with_office",  -- undercover
	born = "FBI_overkill_145",  -- biker heist
	chill_combat = "FBI_overkill_145",  -- safehouse raid
	friend = "FBI_overkill_145",  -- scarface mansion
	flat = "CS_FBI_overkill",  -- panic room
	help = "FBI_overkill_145",  -- prison nightmare
	spa = "FBI_overkill_145",  -- brooklyn 10-10
	moon = "CS_normal",  -- stealing xmas
	run = "CS_normal",  -- heat street
	glace = "CS_FBI_overkill",  -- green bridge
	dah = "CITY_overkill_290",  -- diamond heist
	rvd = "FBI_overkill_145",  -- reservoir dogs
	wwh = "FBI_overkill_145",  -- alaskan deal
	brb = "FBI_overkill_145",  -- brooklyn bank
	nmh = "CITY_overkill_290",  -- no mercy
	sah = "FBI_overkill_145",  -- shacklethorne auction
	chas = "CS_normal",  -- dragon heist
	sand = "CS_FBI_overkill",  -- ukrainian prisoner
	chca = "FBI_overkill_145",  -- black cat
	pent = "FBI_CITY_easy_wish",  -- mountain master
	ranc = "FBI_overkill_145",  -- midland ranch
	trai = "FBI_CITY_easy_wish",  -- lost in transit
	corp = "CITY_overkill_290",  -- hostile takeover
	deep = "CITY_overkill_290",  -- crude awakening
	roberts = "FBI_overkill_145",  -- go bank
}
