return {
	tac_swat_rifle_flank = {
		"original_swats_a",
		"original_swats_b",
		"original_heavys_a",
		"original_heavys_b",
		"original_recon_a",
		"original_recon_b",
		"original_recon_c",
		"original_recon_d",
		"original_reenforce_a",
		"original_reenforce_b",
		"original_reenforce_c",
		"chicken_plate_hrt_a",
		"chicken_plate_hrt_b",
		"chicken_plate_swat_a",
		"chicken_plate_swat_b",
		"chicken_plate_heavy_a",
		"chicken_plate_heavy_b",
	},
	tac_shield_wall = {
		"original_shields_a",
		"original_shields_b",
		"chicken_plate_shield",
	},
	tac_tazer_flanking = {
		"original_tazers_a",
		"original_tazers_b",
		"chicken_plate_taser",
		"chicken_plate_medic",
	},
	tac_bull_rush = {
		"original_tanks_a",
		"original_tanks_b",
		"chicken_plate_tank",
	},
	FBI_spoocs = {
		"original_spoocs_a",
		"original_spoocs_b",
		"chicken_plate_spooc",
	},
}
