return {
	tac_swat_rifle_flank = {
		"tac_swat_rifle",
		"tac_swat_rifle_no_medic",
		"tac_swat_rifle_flank",
		"tac_swat_rifle_flank_no_medic",
		"tac_swat_shotgun_rush",
		"tac_swat_shotgun_rush_no_medic",
		"tac_swat_shotgun_flank",
		"tac_swat_shotgun_flank_no_medic",
		"hostage_rescue",
		"reenforce_init",
		"reenforce_light",
		"reenforce_heavy",
		"marshal_squad",
		"original_swats_a",
		"original_swats_b",
		"original_heavys_a",
		"original_heavys_b",
		"original_recon_a",
		"original_recon_b",
		"original_recon_c",
		"original_recon_d",
		"original_reenforce_a",
		"original_reenforce_b",
		"original_reenforce_c",
		"chicken_plate_hrt_a",
		"chicken_plate_hrt_b",
		"chicken_plate_swat_a",
		"chicken_plate_swat_b",
		"chicken_plate_heavy_a",
		"chicken_plate_heavy_b",
	},
	tac_shield_wall = {
		"tac_shield_wall_ranged",
		"tac_shield_wall_charge",
		"original_shields_a",
		"original_shields_b",
		"chicken_plate_shield",
	},
	tac_tazer_flanking = {
		"tac_tazer_flanking",
		"tac_tazer_charge",
		"original_tazers_a",
		"original_tazers_b",
		"chicken_plate_taser",
		"chicken_plate_medic",
	},
	tac_bull_rush = {
		"tac_bull_rush",
		"original_tanks_a",
		"original_tanks_b",
		"chicken_plate_tank",
	},
	FBI_spoocs = {
		"FBI_spoocs",
		"original_spoocs_a",
		"original_spoocs_b",
		"chicken_plate_spooc",
	},
}
